Repository jsbase/blogmops, pull requests merged in 2020-07, with the labels that each got.

#13 Preview
  .github/labeler.yml
  .github/workflows/cypress.yml
  .github/workflows/labeler.yml
  README.md
  package.json
Labels: backend, dependencies, documentation, feature, frontend

#45 Fix/update
  cypress/plugins/index.js
  cypress/support/commands.js
Labels: bug, frontend, javascript, test

#50 Fix cypress
  .eslintignore
  .github/workflows/cypress.yml
  .gitignore
  .prettierignore
  cypress.json
  package-lock.json
  package.json
  src/server.js
Labels: bug, dependencies, feature, javascript, test

#54 Fix triage runner
  .editorconfig
  .eslintignore
  .eslintrc.json
  .github/labeler.yml
  .github/workflows/build.yml
  .github/workflows/cypress.yml
  .github/workflows/labeler.yml
  .github/workflows/stable.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  cypress.env.json
  cypress/integration/page-navigation.js
  cypress/plugins/index.js
  package-lock.json
  package.json
  postcss.config.js
  rollup.config.js
  src/client.js
  src/components/Bio.svelte
  src/components/Header.svelte
  src/components/Logo.svelte
  src/components/Nav.svelte
  src/node_modules/@sapper/app.mjs
  src/node_modules/@sapper/internal/App.svelte
  src/node_modules/@sapper/internal/error.svelte
  src/node_modules/@sapper/internal/layout.svelte
  src/node_modules/@sapper/internal/manifest-client.mjs
  src/node_modules/@sapper/internal/manifest-server.mjs
  src/node_modules/@sapper/internal/shared.mjs
  src/node_modules/@sapper/server.mjs
  src/node_modules/@sapper/service-worker.js
  src/routes/_error.svelte
  src/routes/_layout.svelte
  src/routes/about.svelte
  src/routes/blog/[slug].json.js
  src/routes/blog/[slug].svelte
  src/routes/blog/_posts.js
  src/routes/blog/index.json.js
  src/routes/blog/index.svelte
  src/routes/blog/posts/hello.md
  src/routes/blog/posts/office.md
  src/routes/index.svelte
  src/server.js
  src/service-worker.js
Labels: backend, bug, dependencies, test

#59 update: preview
  .github/workflows/build.yml
  .github/workflows/cypress.yml
  .github/workflows/wip.yml
  .gitignore
  cypress.env.json
  package-lock.json
  src/node_modules/@sapper/app.mjs
  src/node_modules/@sapper/internal/App.svelte
  src/node_modules/@sapper/internal/error.svelte
  src/node_modules/@sapper/internal/layout.svelte
  src/node_modules/@sapper/internal/manifest-client.mjs
  src/node_modules/@sapper/internal/manifest-server.mjs
  src/node_modules/@sapper/internal/shared.mjs
  src/node_modules/@sapper/server.mjs
Labels: feature, test

#63 Preview
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/issue_label_bot.yaml
  .github/workflows/build.yml
  .github/workflows/config.yml
  .github/workflows/cypress.yml
  cypress.env.json
  package-lock.json
Labels: backend, bug, ci, feature, frontend, javascript, test

#72 Update sapperblog
  package-lock.json
  package.json
  rollup.config.js
  src/routes/blog/_posts.js
  src/utils/markdown.js
Labels: backend, content, feature, frontend, javascript

#89 Preview
  .github/workflows/cypress-io_github_action_runner.yml
  .github/workflows/cypress.yml
  .nvmrc
  cypress.env.json
  cypress.json
  package.json
Labels: documentation, test

#112 Preview
  .github/issue_label_bot.yaml
  .github/labeler.yml
  .github/workflows/build.yml
  .github/workflows/cypress.yml
  .github/workflows/labeler.yml
  .github/workflows/wip.yml
Labels: documentation, test

#114 Preview
  .github/workflows/build.yml
  .github/workflows/cypress.yml
Labels: ci, github_actions

#116 Update README.md
  README.md
Labels: ci, documentation

#117 Preview
  README.md
Labels: documentation
